###
POST  http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email" : "testID",
  "password" : "testpwd",
  "nickname" : "rocky"
}

###
POST  http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email" : "testID",
  "password": "testpwd"
}

###
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0SUQiLCJpYXQiOjE3ODIxMzc1NDEsImV4cCI6MTc4Mjc0MjM0MX0.uY-N-KkFmGoGNQd0q-XxVNYIb8Wp-PVmZcAHlwDYQC4"
}



--------------------------------------------
###
POST http://localhost:3000/api/events HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0SUQiLCJpYXQiOjE3ODI0MDI1NTYsImV4cCI6MTc4MjQwMzQ1Nn0.c4eJ5MayioysX1V3tVeQT1FBRsFysYA3GtIk28p-qTA

{
  "title": "팀 회식 날짜 정하기",
  "description": "이번 달 회식 날짜 투표해요",
  "timeSlots": [
    { "startTime": "2026-07-01 18:00:00", "endTime": "2026-07-01 21:00:00" },
    { "startTime": "2026-07-03 18:00:00", "endTime": "2026-07-03 21:00:00" }
  ]
}

###
GET http://localhost:3000/api/events/4 HTTP/1.1

###
POST http://localhost:3000/api/events/4/vote HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0SUQiLCJpYXQiOjE3ODI0MDI1NTYsImV4cCI6MTc4MjQwMzQ1Nn0.c4eJ5MayioysX1V3tVeQT1FBRsFysYA3GtIk28p-qTA


{
   "votes": [
    { "slotId": 1, "available": true },
    { "slotId": 2, "available": false }
  ]
}

###
PATCH http://localhost:3000/api/events/4/confirm HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0SUQiLCJpYXQiOjE3ODI0MDI1NTYsImV4cCI6MTc4MjQwMzQ1Nn0.c4eJ5MayioysX1V3tVeQT1FBRsFysYA3GtIk28p-qTA

{ "slotId": 1 }